### ISSUE TITLE
Compilation errors with G729 enabled on nixOS 20.03

### ISSUE THREAD

**Issue by mkg20001** [LubosD/twinkle#176]
When compiling with G729 on nixOS 20.03 it gives those errors:
```
/build/source/src/audio/audio_decoder.cpp: In member function 'virtual uint16 t_g729a_audio_decoder::decode(uint8*, uint16, int16*, uint16)':
/build/source/src/audio/audio_decoder.cpp:550:50: error: invalid conversion from 'int16*' {aka 'short int*'} to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
   bcg729Decoder(_context, &payload[done], false, &pcm_buf[done * 8]);
                                                  ^~~~~~~~~~~~~~~~~~
/build/source/src/audio/audio_decoder.cpp:550:68: error: too few arguments to function 'void bcg729Decoder(bcg729DecoderChannelContextStruct*, uint8_t*, uint8_t, uint8_t, uint8_t, uint8_t, int16_t*)'
   bcg729Decoder(_context, &payload[done], false, &pcm_buf[done * 8]);
                                                                    ^
In file included from /build/source/src/audio/audio_decoder.h:42,
                 from /build/source/src/audio/audio_decoder.cpp:20:
/nix/store/1zipc97zlngb2bkyr8nl1ysbijxw1vwz-bcg729-1.0.4/include/bcg729/decoder.h:68:24: note: declared here
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
/build/source/src/audio/audio_decoder.cpp: In member function 'virtual uint16 t_g729a_audio_decoder::conceal(int16*, uint16)':
/build/source/src/audio/audio_decoder.cpp:565:41: error: invalid conversion from 'int16*' {aka 'short int*'} to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
  bcg729Decoder(_context, nullptr, true, pcm_buf);
                                         ^~~~~~~
/build/source/src/audio/audio_decoder.cpp:565:48: error: too few arguments to function 'void bcg729Decoder(bcg729DecoderChannelContextStruct*, uint8_t*, uint8_t, uint8_t, uint8_t, uint8_t, int16_t*)'
  bcg729Decoder(_context, nullptr, true, pcm_buf);
                                                ^
In file included from /build/source/src/audio/audio_decoder.h:42,
                 from /build/source/src/audio/audio_decoder.cpp:20:
/nix/store/1zipc97zlngb2bkyr8nl1ysbijxw1vwz-bcg729-1.0.4/include/bcg729/decoder.h:68:24: note: declared here
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
make[2]: *** [src/audio/CMakeFiles/libtwinkle-audio.dir/build.make:76: src/audio/CMakeFiles/libtwinkle-audio.dir/audio_decoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:232: src/audio/CMakeFiles/libtwinkle-audio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by fbriere** [comment]
Closing as a duplicate of #104. (Twinkle does not currently compile with bcg729 1.0.2+; you will have to either use #152 or downgrade to 1.0.1.)
