### ISSUE TITLE
Code cannot be compiled against bcg729 on Manjaro Linux

### ISSUE THREAD

**Issue by DAC324** [LubosD/twinkle#141]
Hello,

after having installed all dependencies, compiling the code with make fails:

`/home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp: In elementary function »virtual uint16 t_g729a_audio_decoder::decode(uint8*, uint16, int16*, uint16)«:

/home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp:550:50: Error: invalid conversion von »int16*« {aka »short int*«} in »uint8_t« {aka »unsigned char«} [-fpermissive]
   bcg729Decoder(_context, &payload[done], false, &pcm_buf[done * 8]);
                                                  ^~~~~~~~~~~~~~~~~~

/home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp:550:68: Error: too few arguments for function »void bcg729Decoder(bcg729DecoderChannelContextStruct*, uint8_t*, uint8_t, uint8_t, uint8_t, uint8_t, int16_t*)«
   bcg729Decoder(_context, &payload[done], false, &pcm_buf[done * 8]);
                                                                    ^
In file included from /home/gerd/Downloads/twinkle/src/audio/audio_decoder.h:42,
                 from /home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp:20:
/usr/include/bcg729/decoder.h:68:24: Remark: declared here
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~

/home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp: In elementary function »virtual uint16 t_g729a_audio_decoder::conceal(int16*, uint16)«:

/home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp:565:41: Error: invalid conversion von »int16*« {aka »short int*«} in »uint8_t« {aka »unsigned char«} [-fpermissive]
  bcg729Decoder(_context, nullptr, true, pcm_buf);
                                         ^~~~~~~

/home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp:565:48: Error: too few arguments for function »void bcg729Decoder(bcg729DecoderChannelContextStruct*, uint8_t*, uint8_t, uint8_t, uint8_t, uint8_t, int16_t*)«
  bcg729Decoder(_context, nullptr, true, pcm_buf);
                                                ^
In file included from /home/gerd/Downloads/twinkle/src/audio/audio_decoder.h:42,
                 from /home/gerd/Downloads/twinkle/src/audio/audio_decoder.cpp:20:
/usr/include/bcg729/decoder.h:68:24: Remark: declared here
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
make[2]: *** [src/audio/CMakeFiles/libtwinkle-audio.dir/build.make:76: src/audio/CMakeFiles/libtwinkle-audio.dir/audio_decoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:239: src/audio/CMakeFiles/libtwinkle-audio.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

What can I do to remedy that?

**Comment by fbriere** [comment]
Closing as a duplicate of #104.  (Twinkle does not currently compile with bcg729 1.0.2; you will have to downgrade to 1.0.1.)

**Comment by DAC324** [comment]
Confirm. Compiling with 1.0.1 works. Are there plans to adapt Twinkle to the current version 1.0.4 of the G.729 codec?
